#!/bin/bash

set -eu

usage()
{
     cat >&2 <<EOF
Usage: $0 COMMAND [ARG...]

 Commands:
   bind   [-a | --all] [-d | --device-id]
   unbind [-a | --all] [-d | --device-id]
   restore [-a | --all] [-d | --device-id]
   verify [-a | --all] [-d | --device-id] [-m | --driver]
   help [-h]
EOF
    exit 0
}

unbind_from_driver() {
    local gpu=$1
    local existing_driver_name
    local existing_driver

    [ -e "/sys/bus/pci/devices/$gpu/driver" ] || return 0

    existing_driver=$(readlink -f "/sys/bus/pci/devices/$gpu/driver")
    existing_driver_name=$(basename "$existing_driver")

    echo "unbinding device $gpu from driver $existing_driver_name"
    echo "$gpu" > "$existing_driver/unbind"
    echo > /sys/bus/pci/devices/$gpu/driver_override
}

# unbind device from non-target driver
unbind_from_other_driver() {
    local driver=$1
    local gpu=$2
    local existing_driver_name
    local existing_driver

    [ -e "/sys/bus/pci/devices/$gpu/driver" ] || return 0

    existing_driver=$(readlink -f "/sys/bus/pci/devices/$gpu/driver")
    existing_driver_name=$(basename "$existing_driver")

    # return if bound to target driver
    [ "$existing_driver_name" != "$driver" ] || return 0
    echo "unbinding device $gpu from driver $existing_driver_name"
    echo "$gpu" > "$existing_driver/unbind"
    echo > /sys/bus/pci/devices/$gpu/driver_override
}

is_nvidia_gpu_device() {
    local gpu=$1
    # make sure device class is for NVIDIA GPU
    device_class_file=$(readlink -f "/sys/bus/pci/devices/$gpu/class")
    device_class=$(cat "$device_class_file")
    [ "$device_class" == "0x030200" ] || [ "$device_class" == "0x030000" ] || return 1
    return 0
}

is_bound_to_driver() {
    local driver=$1
    local gpu=$2
    local existing_driver_name
    local existing_driver

    # return if not bound to any driver
    [ -e "/sys/bus/pci/devices/$gpu/driver" ] || return 1

    existing_driver=$(readlink -f "/sys/bus/pci/devices/$gpu/driver")
    existing_driver_name=$(basename "$existing_driver")

    echo "existing driver is $existing_driver_name"
    # return if bound to other drivers
    [ "$existing_driver_name" == $driver ] || return 1

    # bound to target driver
    return 0
}

unbind_device() {
    local gpu=$1

    if ! is_nvidia_gpu_device $gpu; then
        return 0
    fi

    echo "unbinding device $gpu"
    unbind_from_driver $gpu
    #for graphics mode, we need to unbind the auxiliary device as well
    aux_dev=$(get_graphics_aux_dev "$gpu")
    if [ "$aux_dev" != "NONE" ]; then
      echo "gpu $gpu is in graphics mode aux_dev $aux_dev"
      unbind_from_driver "$aux_dev"
    fi
}

unbind_all() {
    for dev in /sys/bus/pci/devices/*; do
        read vendor < $dev/vendor
        if [ "$vendor" = "0x10de" ]; then
            local dev_id=$(basename $dev)
            unbind_device $dev_id
        fi
    done
}

bind_driver() {
    local driver=$1
    local gpu=$2

    if ! is_bound_to_driver $driver $gpu; then
      unbind_from_other_driver $driver $gpu
      echo "binding device $gpu to $driver"
      echo $driver > /sys/bus/pci/devices/$gpu/driver_override
      echo "$gpu" > /sys/bus/pci/drivers/$driver/bind
    else
      echo "device $gpu already bound to $driver"
    fi
}

get_graphics_aux_dev() {
    local gpu=$1
    device_class_file=$(readlink -f "/sys/bus/pci/devices/$gpu/class")
    device_class=$(cat "$device_class_file")
    if [ "$device_class" != "0x030000" ]; then
      echo "NONE"
      return
    fi

    if ls "/sys/bus/pci/devices/$gpu" | grep consumer >& /dev/null; then
      aux_dev=$(ls "/sys/bus/pci/devices/$gpu" | grep consumer | awk -Fconsumer:pci: '{print $2}')
      if [ "$aux_dev" == "" ]; then
        echo "NONE"
        return
      fi

      if ls "/sys/bus/pci/devices/$aux_dev/" >& /dev/null; then
        echo "$aux_dev"
        return
      fi
    fi

    echo "NONE"
}

bind_device() {
    local driver=$1
    local gpu=$2

    if ! is_nvidia_gpu_device $gpu; then
        echo "device $gpu is not a gpu!"
        return 0
    fi

    bind_driver "$driver" "$gpu"
    #for graphics mode, we need to bind the auxiliary device as well
    aux_dev=$(get_graphics_aux_dev "$gpu")
    if [ "$aux_dev" != "NONE" ]; then
      echo "gpu $gpu is in graphics mode aux_dev $aux_dev"
      bind_driver "$driver" "$aux_dev"
    fi
}

bind_all() {
    local driver=$1

    for dev in /sys/bus/pci/devices/*; do
        read vendor < $dev/vendor
        if [ "$vendor" = "0x10de" ]; then
            local dev_id=$(basename $dev)
            bind_device $driver $dev_id
        fi
    done
}

verify_device() {
    local driver=$1
    local gpu=$2

    if ! is_nvidia_gpu_device $gpu; then
        return 0
    fi

    if ! is_bound_to_driver $driver $gpu; then
      echo "device $gpu not bound to $driver"
      exit 1
    else
      echo "device $gpu already bound to $driver"
    fi
}

handle_bind() {
    local driver="vfio-pci"

    chroot /host modprobe $driver
    if [ "$DEVICE_ID" != "" ]; then
        bind_device $driver $DEVICE_ID
    elif [ "$ALL_DEVICES" = "true" ]; then
        bind_all $driver
    else
        usage
    fi
}

handle_restore() {
    local driver="nvidia"

    if [ "$DEVICE_ID" != "" ]; then
        bind_device $driver $DEVICE_ID
    elif [ "$ALL_DEVICES" = "true" ]; then
        bind_all $driver
    else
        usage
    fi
}

handle_unbind() {
    if [ "$DEVICE_ID" != "" ]; then
        unbind_device $DEVICE_ID
    elif [ "$ALL_DEVICES" = "true" ]; then
        unbind_all
    else
        usage
    fi
}

verify_all() {
    echo "staring verify all devices"
    for dev in /sys/bus/pci/devices/*; do
        read vendor < $dev/vendor
        if [ "$vendor" = "0x10de" ]; then
            local dev_id=$(basename $dev)
            verify_device $DRIVER $dev_id
        fi
    done
}

if [ $# -eq 0 ]; then
    usage
fi

command=$1; shift
case "${command}" in
    bind) options=$(getopt -o ad: --long all,device-id: -- "$@");;
    unbind) options=$(getopt -o ad: --long all,device-id: -- "$@");;
    restore) options=$(getopt -o ad: --long all,device-id: -- "$@");;
    verify) options=$(getopt -o adm: --long all,device-id,driver: -- "$@");;
    help) options="" ;;
    *) usage ;;
esac
if [ $? -ne 0 ]; then
    usage
fi

eval set -- "${options}"

DEVICE_ID=""
for opt in ${options}; do
    case "$opt" in
    -a | --all) ALL_DEVICES=true; shift 1 ;;
    -d | --device-id) DEVICE_ID=$2; shift 2 ;;
    -m | --driver) DRIVER=$2; shift 2 ;;
    -h | --help) shift;;
    --) shift; break ;;
    esac
done
if [ $# -ne 0 ]; then
    usage
fi

    if [ "$command" = "help" ]; then
        usage
    elif [ "$command" = "bind" ]; then
        handle_bind
    elif [ "$command" = "unbind" ]; then
        handle_unbind
    elif [ "$command" = "restore" ]; then
        handle_restore
    elif [ "$command" = "verify" ]; then
        verify_all
    else
      echo "Unknown function: $command"
      exit 1
    fi
